// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDanVEmYpnDuYswxTAfv0RpbjdVaTi5aYE',
    appId: '1:151866055996:web:c68a87b649aa7d65ac9239',
    messagingSenderId: '151866055996',
    projectId: 'signinonfirebase',
    authDomain: 'signinonfirebase.firebaseapp.com',
    storageBucket: 'signinonfirebase.appspot.com',
    measurementId: 'G-94EZVJNFLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtVWytL09RX1MR29jcGdChOl9jVGGZoJ0',
    appId: '1:151866055996:android:0cd50470207d6d9bac9239',
    messagingSenderId: '151866055996',
    projectId: 'signinonfirebase',
    storageBucket: 'signinonfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcK9_RRCyJgO25Rii-lz86dYfDtKclNyQ',
    appId: '1:151866055996:ios:b241bd784e4c6664ac9239',
    messagingSenderId: '151866055996',
    projectId: 'signinonfirebase',
    storageBucket: 'signinonfirebase.appspot.com',
    androidClientId: '151866055996-318heoo7ekd1etbtq9ec5st42rhfcan0.apps.googleusercontent.com',
    iosClientId: '151866055996-jelcb1lcfvcne4tmubgj7ufmh3us8eak.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcK9_RRCyJgO25Rii-lz86dYfDtKclNyQ',
    appId: '1:151866055996:ios:b241bd784e4c6664ac9239',
    messagingSenderId: '151866055996',
    projectId: 'signinonfirebase',
    storageBucket: 'signinonfirebase.appspot.com',
    androidClientId: '151866055996-318heoo7ekd1etbtq9ec5st42rhfcan0.apps.googleusercontent.com',
    iosClientId: '151866055996-jelcb1lcfvcne4tmubgj7ufmh3us8eak.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDanVEmYpnDuYswxTAfv0RpbjdVaTi5aYE',
    appId: '1:151866055996:web:6b77518267f215fdac9239',
    messagingSenderId: '151866055996',
    projectId: 'signinonfirebase',
    authDomain: 'signinonfirebase.firebaseapp.com',
    storageBucket: 'signinonfirebase.appspot.com',
    measurementId: 'G-P3CFK0ZT1M',
  );
}
